"""Main module."""
import subprocess
import shutil
from pathlib import Path

SETUP_PY = """
# This file was generated by partial_cythonization.
from pathlib import Path
from setuptools import setup
from Cython.Build import cythonize

THIS_DIR = Path(__file__).parent
obfuscate_list_file = Path(THIS_DIR / "_obfuscate_list.txt")

obfuscate_list = obfuscate_list_file.read_text().split("\\n")

setup(
    name='Hello world app',
    ext_modules=cythonize(obfuscate_list)
)
"""


def obfuscate_package(
    src: str, dest: str, compile_all: bool = False, clean: bool = False
):
    """Obfuscate a python package.

    Parameters
    ----------
    src
        Path to the source package.
    dest
        Path to the destination package.
    compile_all
        Whether to compile all python files found in the source package
    clean
        Whether to clean the cythonized files from the source package after obfuscation
    """
    src = Path(src)
    dest = Path(dest)
    shutil.rmtree(dest, ignore_errors=True)
    dest.mkdir(exist_ok=True, parents=True)

    work_dir = src.parent.parent
    src_pkg_dir = src.parent

    included_files = []
    ignored_files = []
    for fp in src.rglob("*"):
        if fp.is_dir():
            continue
        if fp.suffix in (".py", ".txt", ".csv"):
            included_files.append(fp)
        else:
            ignored_files.append(fp)

    py_modules = [each for each in included_files if each.suffix == ".py"]

    print("--- Ignored files: ", ignored_files)
    print("--- Collecting files to obfuscate...")
    to_obfuscate = []
    for mod in py_modules:
        txt = mod.read_text().split("\n")
        if compile_all:
            to_obfuscate.append(str(mod.relative_to(src_pkg_dir)))
        else:
            if txt[0].startswith("# obfuscate_with_cython: True"):
                to_obfuscate.append(str(mod.relative_to(src_pkg_dir)))
    print("--- Found: ", to_obfuscate)

    if not to_obfuscate:
        print("--- No files to obfuscate.")
        return

    (src.parent / "_obfuscate_list.txt").write_text("\n".join(to_obfuscate))
    (src.parent / "setup_generated.py").write_text(SETUP_PY)

    print("--- Running cython on selected files...")
    cmd = ["python", "setup_generated.py", "build_ext", "--inplace"]
    subprocess.run(cmd, cwd=str(src_pkg_dir))
    print("--- Done.")

    print("--- Copying package files with obfuscated modules")
    to_clean = []
    for fp in included_files:
        if str(fp.relative_to(src_pkg_dir)) in to_obfuscate:
            # copy compiled file
            matching_ext = list(fp.parent.glob(fp.stem + "*.so"))
            if matching_ext:
                dest_fp = dest / matching_ext[0].relative_to(src_pkg_dir)
                dest_fp.parent.mkdir(exist_ok=True, parents=True)
                shutil.copy(matching_ext[0], dest_fp)
                to_clean.append(matching_ext[0])
            else:
                raise FileNotFoundError(
                    f"Could not find compiled file for {fp}. This means that cython failed to compile the file."
                )
        else:
            dest_fp = dest / fp.relative_to(src_pkg_dir)
            dest_fp.parent.mkdir(exist_ok=True, parents=True)
            shutil.copy(fp, dest_fp)

    shutil.copytree(src.parent / "tests", dest / "tests")

    if clean:
        for each in to_clean:
            c_file_name = ".".join(each.name.split(".")[:-2]) + ".c"
            print(f"--- Cleaning up: {each} and {c_file_name}")
            each.unlink()
            (each.parent / c_file_name).unlink()
