name: Python tests with uv

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
    - name: setup venv
      run: |
        uv venv
        uv run python --version

    - name: Lint with ruff
      run: |
        uv run --extra lint ruff check
        uv run --extra lint ruff format --check --diff .
        uv run --extra lint ty check partial_cythonization tests 
    - name: Test with pytest
      run: |
        uv run --extra test pytest tests -v
